---
# tasks file for php_server
- name: Update apt and cache if needed
  apt:
    update_cache: True
    upgrade: True
    cache_valid_time: 86400

- name: Add necessary packages
  apt:
    name: software-properties-common
    update_cache: True
    state: latest

- name: Add apt repository
  apt_repository:
    repo: ppa:ondrej/php
    state: present
    update_cache: True

- name: Update the packages
  apt:
    name: software-properties-common
    update_cache: True
    state: latest

- name: install packages
  apt:
    name:
      - git
      - mcrypt
      - nginx
      # - php7.4-cli
      - php8.1
      - php8.1-fpm
      - composer
      - sqlite3
      # - php8.1-extension_name
      - php8.1-common
      - php8.1-mysql
      - php8.1-xml
      - php8.1-xmlrpc
      - php8.1-curl
      - php8.1-gd
      - php8.1-imagick
      - php8.1-cli
      - php8.1-dev
      - php8.1-imap
      - php8.1-mbstring
      - php8.1-opcache
      - php8.1-soap
      - php8.1-zip
      - php8.1-redis
      - php8.1-intl
    update_cache: true
    state: latest
