---
# tasks file for mysql_server

- name: Update apt cache
  apt:
    update_cache: yes

- name: Install necessary python driver
  apt:
    name:
      - python3-pip
      - pymysql
    update_cache: true
    state: latest

- name: Install MySQL Server
  apt:
    name: 
      - mysql-server
      - python-mysqldb
    state: present

- name: Start MySQL Service
  service:
    name: mysql
    state: started
    enabled: yes

- name: Create MySQL database
  mysql_db:
    name: "{{ mysql_db }}"
    state: present

- name: Create MySQL user
  mysql_user:
    name: "{{ mysql_user }}"
    password: "{{ mysql_password }}"
    login_password: "{{ mysql_password }}"
    state: present

- name: See the creds
  debug:
    msg: "{{ mysql_user }} created {{ mysql_db }} with {{ mysql_password }}"

- name: Grant privileges to the user for the database
  mysql_user:
    name: "{{ mysql_user }}"
    priv: "{{ mysql_db }}.*:ALL"
    state: present
