---
# tasks file for mysql_server

- name: Update apt cache
  apt:
    update_cache: yes

- name: Install MySQL Server
  apt:
    name:
      - mysql-server
      - python3-pymysql
    state: present

- name: Start MySQL Service
  service:
    name: mysql
    state: started
    enabled: yes

- name: See the creds
  debug:
    msg: "{{ mysql_user }} created {{ mysql_db }} with {{ mysql_password }}"

- name: Create MySQL database
  mysql_db:
    name: "{{ mysql_db }}"
    state: present
    login_unix_socket: /var/run/mysqld/mysqld.sock
    # login_password: "{{ mysql_password }}"
    # login_user: "{{ mysql_user }}"

# SELECT user, host FROM mysql.user;
# mysql -u vagrant -h localhost -p
- name: Create MySQL user
  mysql_user:
    # name: root
    name: "{{ mysql_user }}"
    password: "{{ mysql_password }}"
    priv: "*.*:ALL"
    host: "localhost"
    state: present
    login_unix_socket: /var/run/mysqld/mysqld.sock

